# Site settings
title: Feng Zhu blog
email: seventtzf@gmail.com
description: "never too late to learn"
baseurl: ""
url: "http://seventt.github.io"
github_username: seventt
linkedin_username: feng-zhu-941507104

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: jekyll-theme-cayman